# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the ROS Demo Malicious Driver
# NB: DO NOT INCLUDE IN ANY PATCH OUTSIDE OF
# DEMO PURPOSES
#
obj-$(CONFIG_ROSDEMO)		+= rosdemo-consumer.o
obj-$(CONFIG_ROSDEMO)		+= rosdemo-leaker.o
